### ISSUE TITLE
ImportError: No module named dijkstra_ryu.py

### ISSUE THREAD

**Issue by raynard131** [knetsolutions/learn-sdn-with-ryu#1]
Hi,
I wanted to try codes from http://csie.nqu.edu.tw/smallko/sdn/dijkstra_ryu.htm
but when I try to run the codes, it doesn't work.

I am using Ubuntu 16.04.4 LTS, python 2.7.12 and 3.5.2, and ryu 4.23.

Here's the error:
`
ray@raihanr:~/ryu/ryu/app$ ryu-manager dijkstra_ryu.py --observe-links
loading app dijkstra_ryu.py
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 9, in <module>
    load_entry_point('ryu==4.23', 'console_scripts', 'ryu-manager')()
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 98, in main
    app_mgr.load_apps(app_lists)
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 415, in load_apps
    cls = self.load_app(app_cls_name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 392, in load_app
    mod = utils.import_module(name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/utils.py", line 104, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named dijkstra_ryu.py
`

I already tried using this:
`
:~$ryu-manager ryu/ryu/app/dijkstra_ryu.py --observe-links
`

But it showing a different error:
`
ImportError: Import by filename is not supported.
`
Also, I already checked every module and not missing any part.
Is there someone who can help me?
Best,
Ray

**Comment by sureshkvl** [comment]
try
ryu-manager --observe-links  dijkstra_ryu.py

**Comment by raynard131** [comment]
@sureshkvl : it still creating the same error

**Comment by raghdaaljaff** [comment]
@raynard131 did you solve the error?

**Comment by raynard131** [comment]
@raghdaaljaff I didn't. Maybe you can help me?

**Comment by raghdaaljaff** [comment]
I tried to apply but I think the error in the code of dijkstra bcoz I tried too in Ubuntu 16 and python version 2.7 and the mininet eel 
If I found the solution I can let you know and you too if you find the solution tell me thanks .

Regards.

**Comment by raynard131** [comment]
@raghdaaljaff when I try the other pojects, they are creating the same error for the ryu controller codes. but when I try the topology codes, it works fine. Let knowing each other then

**Comment by raghdaaljaff** [comment]
Yeah exactly the error in the ryu source code , ok I will let you know if I find solution and you too ,thanks 

Regards.

**Comment by raynard131** [comment]
@raghdaaljaff I FOUND IT. the problem is in the spacing rule. the codes are not using space in the right way. so, we need to change the space that is 4 times when codes are inside the definition, for, if, and etc.

**Comment by raghdaaljaff** [comment]
@raynard131 thanks for replying can you attach  the code after modify bcoz iam stilling to  face the problem

**Comment by raynard131** [comment]
@raghdaaljaff when there is a code inside of for, if, class, definiton, and others you need to make four spaces to be recognized by python
``
from ryu.base import app_manager
from ryu.controller import mac_to_port
from ryu.controller import ofp_event
from ryu.controller.handler import CONFIG_DISPATCHER, MAIN_DISPATCHER
from ryu.controller.handler import set_ev_cls
from ryu.ofproto import ofproto_v1_3
from ryu.lib.mac import haddr_to_bin
from ryu.lib.packet import packet
from ryu.lib.packet import ethernet
from ryu.lib.packet import ether_types
from ryu.lib import mac
 
from ryu.topology.api import get_switch, get_link
from ryu.app.wsgi import ControllerBase
from ryu.topology import event, switches
from collections import defaultdict
 
#switches
switches = []
 
#mymac[srcmac]->(switch, port)
mymac={}
 
#adjacency map [sw1][sw2]->port from sw1 to sw2
adjacency=defaultdict(lambda:defaultdict(lambda:None))
 
def minimum_distance(distance, Q):
    min = float('Inf')
    node = 0
    for v in Q:
        if distance[v] < min:
            min = distance[v]
            node = v
    return node
 
def get_path (src,dst,first_port,final_port):
    #Dijkstra's algorithm
    print "get_path is called, src=",src," dst=",dst, " first_port=", first_port, " final_port=", final_port
    distance = {}
    previous = {}
 
    for dpid in switches:
        distance[dpid] = float('Inf')
        previous[dpid] = None
 
    distance[src]=0
    Q=set(switches)
    print "Q=", Q
   
    while len(Q)>0:
        u = minimum_distance(distance, Q)
        Q.remove(u)
   
        for p in switches:
            if adjacency[u][p]!=None:
                w = 1
                if distance[u] + w < distance[p]:
                    distance[p] = distance[u] + w
                    previous[p] = u
 
    r=[]
    p=dst
    r.append(p)
    q=previous[p]
    while q is not None:
        if q == src:
            r.append(q)
            break
        p=q
        r.append(p)
        q=previous[p]
 
    r.reverse()
    if src==dst:
        path=[src]
    else:
        path=r
 
    # Now add the ports
    r = []
    in_port = first_port
    for s1,s2 in zip(path[:-1],path[1:]):
        out_port = adjacency[s1][s2]
        r.append((s1,in_port,out_port))
        in_port = adjacency[s2][s1]
    r.append((dst,in_port,final_port))
    return r
 
class ProjectController(app_manager.RyuApp):
    OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]
 
    def __init__(self, *args, **kwargs):
        super(ProjectController, self).__init__(*args, **kwargs)
        self.mac_to_port = {}
        self.topology_api_app = self
        self.datapath_list=[]
  
    # Handy function that lists all attributes in the given object
    def ls(self,obj):
        print("\n".join([x for x in dir(obj) if x[0] != "_"]))
 
    def add_flow(self, datapath, in_port, dst, actions):
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser      
        match = datapath.ofproto_parser.OFPMatch(in_port=in_port, eth_dst=dst)        
        inst = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS, actions)] 
        mod = datapath.ofproto_parser.OFPFlowMod(datapath=datapath, match=match, cookie=0, command=ofproto.OFPFC_ADD, idle_timeout=0, hard_timeout=0, priority=ofproto.OFP_DEFAULT_PRIORITY, instructions=inst)
        datapath.send_msg(mod)
 
    def install_path(self, p, ev, src_mac, dst_mac):
        print "install_path is called"
        #print "p=", p, " src_mac=", src_mac, " dst_mac=", dst_mac
        msg = ev.msg
        datapath = msg.datapath
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser
        for sw, in_port, out_port in p:
            #print src_mac,"->", dst_mac, "via ", sw, " in_port=", in_port, " out_port=", out_port
            match=parser.OFPMatch(in_port=in_port, eth_src=src_mac, eth_dst=dst_mac)
            actions=[parser.OFPActionOutput(out_port)]
            datapath=self.datapath_list[int(sw)-1]
            inst = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS , actions)]
            mod = datapath.ofproto_parser.OFPFlowMod(datapath=datapath, match=match, idle_timeout=0, hard_timeout=0, priority=1, instructions=inst)
            datapath.send_msg(mod)
 
    @set_ev_cls(ofp_event.EventOFPSwitchFeatures , CONFIG_DISPATCHER)
    def switch_features_handler(self , ev):
        print "switch_features_handler is called"
        datapath = ev.msg.datapath
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser
        match = parser.OFPMatch()
        actions = [parser.OFPActionOutput(ofproto.OFPP_CONTROLLER, ofproto.OFPCML_NO_BUFFER)]
        inst = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS ,
actions)]
        mod = datapath.ofproto_parser.OFPFlowMod(datapath=datapath, match=match, cookie=0, command=ofproto.OFPFC_ADD, idle_timeout=0, hard_timeout=0, priority=0, instructions=inst)
        datapath.send_msg(mod)
 
    @set_ev_cls(ofp_event.EventOFPPacketIn, MAIN_DISPATCHER)
    def _packet_in_handler(self, ev):
        msg = ev.msg
        datapath = msg.datapath
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser
        in_port = msg.match['in_port']
 
        pkt = packet.Packet(msg.data)
        eth = pkt.get_protocol(ethernet.ethernet)
        #print "eth.ethertype=", eth.ethertype
 
        #avodi broadcast from LLDP
        if eth.ethertype==35020:
            return
 
        dst = eth.dst
        src = eth.src
        dpid = datapath.id
        self.mac_to_port.setdefault(dpid, {})
 
        if src not in mymac.keys():
            mymac[src]=( dpid,  in_port)
            #print "mymac=", mymac
 
        if dst in mymac.keys():
            p = get_path(mymac[src][0], mymac[dst][0], mymac[src][1], mymac[dst][1])
            print p
            self.install_path(p, ev, src, dst)
            out_port = p[0][2]
        else:
            out_port = ofproto.OFPP_FLOOD
       
        actions = [parser.OFPActionOutput(out_port)]
 
        # install a flow to avoid packet_in next time
        if out_port != ofproto.OFPP_FLOOD:
            match = parser.OFPMatch(in_port=in_port, eth_src=src, eth_dst=dst)
       
        data=None
        if msg.buffer_id==ofproto.OFP_NO_BUFFER:
            data=msg.data
 
        out = parser.OFPPacketOut(datapath=datapath, buffer_id=msg.buffer_id, in_port=in_port, actions=actions, data=data)
        datapath.send_msg(out)
    
    @set_ev_cls(event.EventSwitchEnter)
    def get_topology_data(self, ev):
        global switches
        switch_list = get_switch(self.topology_api_app, None)  
        switches=[switch.dp.id for switch in switch_list]
        self.datapath_list=[switch.dp for switch in switch_list]
        #print "self.datapath_list=", self.datapath_list
        print "switches=", switches
 
        links_list = get_link(self.topology_api_app, None)
        mylinks=[(link.src.dpid,link.dst.dpid,link.src.port_no,link.dst.port_no) for link in links_list]
        for s1,s2,port1,port2 in mylinks:
            adjacency[s1][s2]=port1
            adjacency[s2][s1]=port2
            #print s1,s2,port1,port2
``

**Comment by aidakrr** [comment]
im facing the error, the function minimum_distance always give node=0, can anyone help me with this?

![image](https://user-images.githubusercontent.com/59154303/78261862-facbf180-7529-11ea-891e-4a28c18a5faf.png)

**Comment by juanpinem** [comment]
i still have the same problem, the icon files .py is different.
![Capture](https://user-images.githubusercontent.com/30331601/78472925-dc9f0500-7766-11ea-8529-d33d86ef6b77.JPG)
![Capture2](https://user-images.githubusercontent.com/30331601/78472984-6c44b380-7767-11ea-9996-1a71af01729c.JPG)

**Comment by juanpinem** [comment]
![Capture2](https://user-images.githubusercontent.com/30331601/78472970-49b29a80-7767-11ea-930c-19572f743058.JPG)

**Comment by Naimullah** [comment]
Sir kindly help me i use dijkstra in ryu it give me the above error 
how can i solve this problem  ImportError: No module named dijkstra_ryu.py

**Comment by robertbotez** [comment]
Hi. I get an error when I tried to ping hosts which are connected to different switches. For example if I have a layer-2 tree topology created with mininet: sudo mn --topo tree,2 --controller remote and tried to ping h3 from h1, I got the following error:

('get_path is called, src=', 3, ' dst=', 2, ' first_port=', 1, ' final_port=', 1)
('Q=', set([1, 2, 3]))
[(3, 1, None), (2, None, 1)]
install_path is called
ProjectController: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/ubuntu/ryu/ryu/app/dijkstra.py", line 155, in _packet_in_handler
    self.install_path(p, ev, src, dst)
  File "/home/ubuntu/ryu/ryu/app/dijkstra.py", line 116, in install_path
    datapath.send_msg(mod)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ryu/controller/controller.py", line 442, in send_msg
    msg.serialize()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ryu/ofproto/ofproto_parser.py", line 270, in serialize
    self._serialize_body()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 2747, in _serialize_body
    inst.serialize(self.buf, offset)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 2939, in serialize
    a.serialize(buf, action_offset)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 3049, in serialize
    offset, self.type, self.len, self.port, self.max_len)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ryu/lib/pack_utils.py", line 25, in msg_pack_into
    struct.pack_into(fmt, buf, offset, *args)
error: cannot convert argument to integer

Does anybody can help me? Thank you.
